; Moment PIMSLO — Point-and-Shoot Camera Firmware
; Target: Seeed Studio XIAO ESP32-S3 Sense

[platformio]
default_envs = xiao_esp32s3

[env:xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = espidf

board_build.partitions = partitions.csv
board_build.flash_size = 8MB
board_build.sdkconfig_defaults = sdkconfig.defaults

build_flags =
    -DBOARD_HAS_PSRAM
    -DCONFIG_SPIRAM_USE_MALLOC=1
    -DLOG_LOCAL_LEVEL=ESP_LOG_INFO
    -DCONFIG_SCCB_CLK_FREQ=100000
    -DCONFIG_CAMERA_DMA_BUFFER_SIZE_MAX=32768
    -DCONFIG_OV5640_SUPPORT=1
    -DCONFIG_OV3660_SUPPORT=1
    -DCONFIG_OV2640_SUPPORT=1
    -DCONFIG_CAMERA_TASK_STACK_SIZE=8192

lib_deps =
    espressif/esp32-camera@^2.0.4               ; OV5640/OV3660 camera driver (GDMA patched)
    codewitch-honey-crisis/htcw_rmt_led_strip@^0.2.2  ; WS2812 NeoPixel via RMT

lib_ldf_mode = deep
extra_scripts =
    pre:scripts/inject_version.py
    pre:scripts/patch_camera_lib.py

board_build.cmake_extra_args = -DCMAKE_BUILD_PARALLEL_LEVEL=4

upload_flags = --before=no_reset

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
